name: Docker Image CI

on:
  push:
    branches: [ SCAMP Assessment 2 ]
  pull_request:
    branches: [ SCAMP Assessment 2 ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: rearrange data with 80% degree of accuracy
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
